driver:
  name: vagrant
  cachier: true
  synced_folders:
    - [ '../fusionauth-install', '/media/shared/' ]

provisioner:
  name: shell

platforms:
- name: bento/ubuntu-16.04
- name: bento/ubuntu-18.04
- name: bento/centos-7.4

verifier:
  name: serverspec

suites:
- name: default
